version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]

stack_name = "jira-github-auto-labels"
s3_prefix = "jira-github-auto-labels"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
